default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000
  host: <%= ENV['DATABASE_HOST'] || 'db' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  encoding: unicode

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'onboarding_development' %>

test:
  <<: *default
  database: onboarding_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  database: <%= ENV['DATABASE_NAME'] || 'onboarding_production' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
